version: '3.5'

services:
  integrator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '3001:443'
    networks:
      - integrator_network
    restart: always
  redis-db:
    image: redis:6.0-rc3-alpine
    command: ['redis-server', '--appendonly', 'yes', '--requirepass', '12345']
    ports:
      - '6379:6379'
    restart: always
    networks:
      - integrator_network
  
networks:
  integrator_network:
    driver: bridge
