version: '3.5'

services:
  redis-db:
    image: redis:6.0-rc3-alpine
    command: ['redis-server', '--appendonly', 'yes', '--requirepass', '12345']
    ports:
      - '6379:6379'
    restart: always
    networks:
      - integrator_network
    volumes:
      - redis-data:/data
  integrator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - integrator_network
    restart: always
    depends_on: [redis-db]
  
networks:
  integrator_network:
    driver: bridge

volumes:
  redis-data:
    